name: "Melchor Sanchez-Martinez"
description: "The Personal Homepage for Melchor Sanchez-Martinez"

#url: "http://melchorsanchezmartinez.com"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
