name: "Melchor Sanchez-Martinez"
description: "The Personal Homepage for Melchor Sanchez-Martinez"

url: "http://msanchezmartinez.com"

gems: [jekyll-paginate, jekyll-seo-tag]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/
        - Readme.md
        - License
        
collections:
        bio:
                output: true
        publications:
                output: true

# Icons
  #rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: sanchezmartinezmelchor@gmail.com # Full email address, e.g. "sam@example.com"
  gitlab: "msanmar"
  github: "MelchorSanchez"
  linkedin: https://www.linkedin.com/in/azmirfakkri/ # Full URL
  twitter: "melsanm"
  ORCD: "0000-0002-3674-8577"

  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    reddit: true
    linkedin: true
    email: true

  # Scripts / Features
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: melchor_sanchez
  katex: true # Enable if using math markup

  special_page:
    search:
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true

  # Post navigation
  post_navigation: true