name: "Melchor Sanchez-Martinez"
description: "The Personal Homepage for Melchor Sanchez-Martinez"

url: "http://msanchezmartinez.com"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/
        
collections:
        bio:
                output: true
        publications:
                output: true
