name: "Melchor Sanchez-Martinez"
description: "The Personal Homepage for Melchor Sanchez-Martinez. A research scientist with experience in project management and science management, passionate about science writing, communication and dissemination"
url: "http://msanchezmartinez.com"
logo: 'avatar.png'

plugins: [jekyll-paginate, jekyll-seo-tag]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        bio:
                output: true
        publications:
                output: true

# About/contact
author:
  name: Melchor Sanchez-Martinez
  description: A <strong>research scientist with experience in project management and science management, passionate about science writing, communication and disseminationr</strong>.
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    twitter:   https://twitter.com/melsanm
    linkedin:  https://www.linkedin.com/in/melchorsanchezmartinez
    github:    https://github.com/MelchorSanchez
    gitlab:    https://gitlab.com/msanmar
    twitter:   https://twitter.com/Li_Zhihao
    email:     sanchezmartinezmelchor@gmail.com

nav:
  Home:
    - '/'
  Bio:
    - '/about/'
  Publications:
    - 'publications'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  Contact:
    - '/contact/'

tags_page: '/blog/tags/'
categories_page: '/blog/categories/'


tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty


excerpt_separator: '<!-- excerpt-end -->'
